name: Build Project

on: push

jobs:
  compile:
    runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: javac -sourcepath src -d bin src/*/*.java
